# Generated by Django 5.1.7 on 2025-03-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predators', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prey',
        ),
        migrations.RemoveField(
            model_name='predator',
            name='species',
        ),
        migrations.AddField(
            model_name='predator',
            name='animal_class',
            field=models.CharField(choices=[('mammal', 'Mammal'), ('amphibian', 'Amphibian'), ('bird', 'Bird'), ('fish', 'Fish'), ('reptile', 'Reptile')], default='mammal', max_length=50),
        ),
        migrations.AddField(
            model_name='predator',
            name='diet',
            field=models.CharField(choices=[('omnivore', 'Omnivore'), ('herbivore', 'Herbivore'), ('carnivore', 'Carnivore'), ('N/A', 'N/A')], default='Herbivore', max_length=50),
        ),
        migrations.AddField(
            model_name='predator',
            name='prey',
            field=models.CharField(default='Unknown!', max_length=50),
        ),
        migrations.AlterField(
            model_name='predator',
            name='name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
