# Generated by Django 5.1.7 on 2025-03-14 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predators', '0003_predator_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=50)),
                ('animal_class', models.CharField(choices=[('mammal', 'Mammal'), ('amphibian', 'Amphibian'), ('bird', 'Bird'), ('fish', 'Fish'), ('reptile', 'Reptile')], default='mammal', max_length=50)),
                ('diet', models.CharField(choices=[('omnivore', 'Omnivore'), ('herbivore', 'Herbivore'), ('carnivore', 'Carnivore'), ('N/A', 'N/A')], default='Herbivore', max_length=50)),
                ('predator_of_prey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunted_preys', to='predators.predator')),
            ],
        ),
    ]
